[package]
name = "bath-monitor-firmware"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
embassy-executor = { version = "0.10.0" }
embassy-time = { version = "0.5.1" }
embassy-rp = { version = "0.10.0", features = ["unstable-pac", "time-driver", "critical-section-impl", "rp2040", "executor-thread", "executor-interrupt"] }
embassy-net = { version = "0.9.1", features = ["tcp", "dns", "dhcpv4"] }
embassy-sync = { version = "0.8.0" }
embassy-usb-logger = { version = "0.6.0" }

cyw43 = { version = "0.7.0" }
cyw43-pio = { version = "0.10.0" }
smart-leds = { version = "0.4.0" }

reqwless = { version = "0.14.0", default-features = false }
embedded-io-async = { version = "0.7.0" }

cortex-m = { version = "0.7.6", features = ["inline-asm"] }
cortex-m-rt = { version = "0.7.0" }
panic-halt = { version = "1.0.0" }

static_cell = { version = "2.1.1" }
heapless = { version = "0.9.3" }
log = { version = "0.4.34" }
portable-atomic = { version = "1", features = ["critical-section"] }

[profile.release]
debug = true
lto = true
opt-level = "s"
